name: Package Application with Pyinstaller for Ubuntu 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: PyInstaller Linux
      uses: JackMcKew/pyinstaller-action-linux@0.1.4
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: uasssoftwarelinux
        path: src/dist/linux